package com.hostel.management.security;

import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;
import java.security.SecureRandom;

public class AESUtil {

    private static final String ALGORITHM = "AES";

    // generate AES-256 key
    public static SecretKey generateKey() throws Exception {
        KeyGenerator generator = KeyGenerator.getInstance(ALGORITHM);
        generator.init(256, new SecureRandom()); // 256 bit key
        return generator.generateKey();
    }

    // Encrypt file bytes
    // Converts original file bytes into encrypted bytes
    public static byte[] encrypt(byte[] data, SecretKey key) throws Exception {
        Cipher cipher = Cipher.getInstance(ALGORITHM);

        // prepares cipher for encryption using the secret key generated by above method
        // Cipher : a secret code
        cipher.init(Cipher.ENCRYPT_MODE, key);


        return cipher.doFinal(data);
    }

    // Decrypt file bytes
    // converts encrypted data back to original file
    public static byte[] decrypt(byte[] encryptedData, SecretKey key) throws Exception {
        Cipher cipher = Cipher.getInstance(ALGORITHM);
        cipher.init(Cipher.DECRYPT_MODE, key);
        return cipher.doFinal(encryptedData);
    }

    // convert key to bytes
    // key is stored as byte array because db cannot store SecretKey objects
    // converts key to byte[] for DB storage
    public static byte[] keyToBytes(SecretKey key) {
        return key.getEncoded();
    }

    // restore key from bytes
    // rebuilds key from stored bytes
    public static SecretKey bytesToKey(byte[] keyBytes) {
        return new SecretKeySpec(keyBytes, ALGORITHM);
    }
}
